version: '3'

services:
  mysql_judge_backend:
    container_name: mysql_judge_backend_demo
    image: vinhbh/mysql-judge-service:2.1
    command: npm run dev
    networks:
      - sql-lab-server_sql_lab_network
    depends_on:
      - mysql_judge_db
    environment:
      - RABBITMQ_URL=amqp://rabbitmq_sql_demo

  mysql_judge_backend_2:
    container_name: mysql_judge_backend_2_demo
    image: vinhbh/mysql-judge-service:2.1
    command: npm run dev
    networks:
      - sql-lab-server_sql_lab_network
    depends_on:
      - mysql_judge_db    
    environment:
      - RABBITMQ_URL=amqp://rabbitmq_sql_demo

  mysql_judge_db:
    image: mysql:8.0.37
    restart: always
    container_name: mysql_judge_db_demo
    environment:
      MYSQL_ROOT_PASSWORD: SqlLab2024!
      MYSQL_DATABASE: base_issue_data
    networks:
      - sql-lab-server_sql_lab_network
    volumes:
      - ./init2.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_db_data_v11:/var/lib/mysql

volumes:
  mysql_db_data_v11:

networks:
  sql-lab-server_sql_lab_network:
    external: true